### ISSUE TITLE
建议更新一下READEME

### ISSUE THREAD

**Issue by thredreams** [OpenBGBenchmark/OpenBG500#3]
从天池那边过来的，发现两边对数据集的格式描述不同，下载后发现这边的README里是错的。实际上是tsv格式。同时谷歌云盘似乎也失效了404

**Comment by CheaSim** [comment]
不好意思， OpenBG500是使用不同的seed采样和格式的一份数据集。 链接已经更新。

**Comment by zxlzr** [comment]
您好，readme已更新
